version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.d/nginx.conf
      - ./csjse-app:/csjse-app
  # mysql:
  #   image: mariadb:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: <PASSWORD>
  #     MYSQL_USER: <USER>
  #     MYSQL_PASSWORD: <PASSWORD>
  #     MYSQL_DATABASE: "CSJSE"
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #   ports:
  #     - 5000:5000
